<?php

/**
 * Implements hook_permission
 */
function bht_permission() {
  // Add an extra access check to manage display page.
  return array(
    'use manage display' => array(
      'title' => t('Use manage display'),
    ),
  );
}

/**
 * Implements hook_menu
 */
function bht_menu() {
  $items = array();

  // Create a main admin menu item.
  $items['admin/config/bht'] = array(
    'title' => 'BHT',
    'description' => 'Configure BHT modules',
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
    'weight' => 50,
    'file path' => drupal_get_path('module', 'system'),
    'file' => 'system.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_menu_alter
 */
function bht_custom_menu_alter(&$items) {
  // This adds an access check for the manage display pages.
  $items['user/%user/display']['access arguments'] = array('use manage display');
  $items['node/%node/display']['access arguments'] = array('use manage display');
  $items['taxonomy/term/%taxonomy_term/display']['access arguments'] = array('use manage display');

  // Redirect default /node to frontpage.
  $items['node']['page callback'] = 'drupal_goto';
  $items['node']['page arguments'] = array('<front>');
}

/**
 * Implements hook_form_alter().
 */
function bht_form_optimizer_form_alter(&$form, &$form_state, $form_id) {
  // Add BEM styling to user forms
  switch ($form_id) {
    case 'user_login':
      $form['#attributes'] = array('class' => array('user__form', 'user__form--login'));
      break;

    case 'user_pass':
      $form['#attributes'] = array('class' => array('user__form', 'user__form--password'));
      break;

    case 'user_register_form':
      $form['#attributes'] = array('class' => array('user__form', 'user__form--register'));
      unset($form['account']['#type']);
      break;

    case 'user_profile_form':
      $form['#attributes'] = array('class' => array('user__form', 'user__form--profile'));
      unset($form['account']['#type']);
      break;

    default:
      break;
  }
}
