<?php
/**
 * @file
 * Adds custom functionality, configuration and structure to the site.
 */

/**
 * Define any constants here.
 */
//define('BHT_VARIABLE', variable_get('bht_variable', ''));

/**
 * Implements hook_permission().
 */
function bht_permission() {
  // Add an extra access check to manage display page.
  return array(
    'use manage display' => array(
      'title' => t('Use manage display'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function bht_menu() {
  $items = array();

  // Create a main admin menu item.
  $items['admin/config/bht'] = array(
    'title' => 'BHT',
    'description' => 'Configure BHT modules',
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
    'weight' => 50,
    'file path' => drupal_get_path('module', 'system'),
    'file' => 'system.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_menu_alter().
 */
function bht_custom_menu_alter(&$items) {
  // This adds an access check for the manage display pages.
  $items['user/%user/display']['access arguments'] = array('use manage display');
  $items['node/%node/display']['access arguments'] = array('use manage display');
  $items['taxonomy/term/%taxonomy_term/display']['access arguments'] = array('use manage display');

  // Redirect default /node to frontpage.
  $items['node']['page callback'] = 'drupal_goto';
  $items['node']['page arguments'] = array('<front>');
}

/**
 * Define blocks.
 */
module_load_include('inc', 'bht_custom', 'bht_custom.blocks');

/**
 * Alter forms.
 */
module_load_include('inc', 'bht_custom', 'bht_custom.forms');

/**
 * Alter entities and/or add view modes to them.
 */
module_load_include('inc', 'bht_custom', 'bht_custom.entities');

/**
 * Generate content.
 */
module_load_include('inc', 'bht_custom', 'bht_custom.content');

/**
 * Add theme templates and/or hooks.
 */
module_load_include('inc', 'bht_custom', 'bht_custom.theme');

/**
 * Define tokens.
 */
module_load_include('inc', 'bht_custom', 'bht_custom.tokens');

/**
 * Add module helper functions.
 */
module_load_include('inc', 'bht_custom', 'bht_custom.helper');
